all:
	g++ -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 Test.cpp -I ./ -I ../FileStorage/
	g++ -o Test -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++11 Main.cpp -I ./ -I ../FileStorage/
